// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240912144536_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebAPI.Entities.Musico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Musicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Gustavo Cerati"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Indio Solari"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Miranda"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Charly García"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Divididos"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Mercedes Sosa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
